### ISSUE TITLE
Investigate the use of templates

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres#10]
![image](https://user-images.githubusercontent.com/10214025/80930860-c2e5f180-8de8-11ea-87d8-4383d1fc6926.png)

Question: can we use this for more than just languages? If so, can we enable some of our plugins without polluting the public schema?

Would love a good investigation into templates, what they do, and how they work. Once we have all the details I think it's worth a blog post too.

**Comment by kiwicopple** [comment]
Also note that we can add global functions/extensions etc in `pg_catalog`: https://stackoverflow.com/questions/12986368/installing-postgresql-extension-to-all-schemas

However this is NOT recommended. the catalogs are generally readonly. Adding this note here for future reference

**Comment by dragarcia** [comment]
# template1

- `CREATE DATABASE` works by using an existing database as a baseline or mould.
- This standard database is name *template1* in PostgreSQL.
    - Modifying this template is therefore not advised to avoid any mishaps when creating new databases.
- Adding extensions to this database will propagate to subsequent databases created with `CREATE DATABASE`.
    - This should include both traditional plug-ins and procedural languages.
- The default database *postgres* is actually just a copy of *template1*, and can be dropped at any time.

## Cleaning

- Best way is to manually uninstall or drop anything that has been installed into the template.
- It is possible for you to delete the database and recreate it.
    - However, you run the risk of forgetting to recreate it and effectively breaking `CREATE DATABASE`

# template0

- Another standard database that exists by default along with *template1.*
- It contains the same data as the initial contents of *template1*.
- This acts as the fallback to *template1* when modifications have been applied to it.
- Hence, this database should never be modified in any way as soon as the database cluster has been initialised.

## Applications

- Creating a database that does not contain any modifications applied to *template1*. Useful when a restoration of a pg_dump dump is needed to be done. This is to minimise any conflicts that may occur with anything that may have been added into *template1.*

```sql
CREATE DATABASE dbname TEMPLATE template0;
```

- Can be used to specify new encodings and locale settings. Using *template1* will force the database to use the same settings and trying to change either the encoding or locale settings results in an error when creating a new database with it.

```sql
-- Will succeed
CREATE DATABASE dbname TEMPLATE template0 ENCODING 'SQL_ASCII';

-- Will return an error
CREATE DATABASE dbname ENCODING 'SQL_ASCII';
```

# Creating New Templates

- It is possible to create new templates.
- Alternatively, existing databases can be used as a template when creating new databases.

```sql
CREATE DATABASE dbname TEMPLATE existing_db_name;
```

## How

- There exists a catalog `pg_database` which lists out all available databases in the cluster.
- The column `datistemplate` indicates that the database is to be utilised as a template.
    - If set, database can be cloned by any user with `CREATEDB` privileges.
    - Else, only superusers and owners of the database can clone it.
- The column `datallowconn` indicates whether connections are allowed to the database.
    - If set to `false` , connections are
    - This prevents the database from being modified.
    - `datallowcon` for *template0* is set to `false` by default.

## Limitation

- When using this to create a copy of a database, no other sessions can be connected during the process.
- Likewise, `CREATE DATABASE` fails when other connections exist upon start.
    - This applies to *template1* as well if a connection is established with the that database.
- If you want to duplicate a database but still maintain your connections (for eg. a production database), it would be more ideal to use `pg_dump` instead.

## Application

- Create template databases with extensions based on your needs.
- Create databases using these templates.

# Extensions

```sql
CREATE EXTENSION extension_name
```

- Extensions in this context apply to both plug-ins and procedural languages.
- Extensions are not applied to the entire database.
- If a schema is not mentioned, extension will be applied to the `public` schema.

# Recommendation

- Templates are useful to preset:
    - Tables
    - Data
    - Plug-ins (pgcrypto, postGIS, etc.)
    - Procedural Languages (plpythonu, plv8, etc.)
- Although we can modify *template1* to easily set up databases with these preset options, it would be better to create template/s to use to achieve this.
- This would be to prevent bloating up of *template1* which could be difficult to clean up over time.

---

### Sources

[PostgreSQL: Documentation: 12: 22.3. Template Databases](https://www.postgresql.org/docs/current/manage-ag-templatedbs.html)

[PostgreSQL: Documentation: 12: 51.15. pg_database](https://www.postgresql.org/docs/current/catalog-pg-database.html)

[PostgreSQL Tips: Template Databases - IBM Cloud Blog](https://www.ibm.com/cloud/blog/postgresql-tips-template-databases)

[PostgreSQL Tips: Template Databases](https://www.compose.com/articles/postgresql-tips-template-databases/)

[Exploring the Default Postgres Template Databases](https://hashrocket.com/blog/posts/exploring-the-default-postgres-template-databases)

[PostgreSQL: Documentation: 12: CREATE EXTENSION](https://www.postgresql.org/docs/current/sql-createextension.html)

**Comment by kiwicopple** [comment]
Amazing work Angelico. This is pretty interesting. 

I think that we probably should change template1 for any non-modifying extensions like the Procedural Languages (plpythonu, plv8, etc.). This is obviously what AWS do - when you start a new schema, they are already enabled

But we should avoid modifying the template with anything that will pollute new schemas (add tables, functions etc)

Will be cool to set up various templates that our users could get started with though. Like a fast way to get set up with PostGIS etc. I see that the syntax is actually "CREATE DATABASE" and not "CREATE SCHEMA". So it seems we would have to reconfigure our app a bit to support multiple databases (at the moment we assume one "Database" per server

**Comment by dragarcia** [comment]
**I think that we probably should change template1 for any non-modifying extensions like the Procedural Languages (plpythonu, plv8, etc.). This is obviously what AWS do - when you start a new schema, they are already enabled**

Noted on this. We can queue this up for the next version.

---

**But we should avoid modifying the template with anything that will pollute new schemas (add tables, functions etc)**

If I understood what I've read, what we can do is remove the option to connect to _template1_ by setting `datallowcon` to `false` for this database. This will prevent any further manipulation to the template database. The eventual user of the database however can just switch `datallowcon` back to `true` if they so choose, but this will involve a lot of deliberate effort.

---

**Will be cool to set up various templates that our users could get started with though. Like a fast way to get set up with PostGIS etc. I see that the syntax is actually "CREATE DATABASE" and not "CREATE SCHEMA". So it seems we would have to reconfigure our app a bit to support multiple databases (at the moment we assume one "Database" per server**

A quick glance and unfortunately there does not seem to be any template functionality whatsoever for schemas. If the use case is for individual extensions, I think the most straightforward way is through `CREATE EXTENSION`, provided that the user remains in the same database. 

Where database templates could probably shine is setting templates for either a database that has all plug-ins enabled, or plug-ins that either highly synergise with one another or are often used in conjunction with one another. It therefore makes it easier for users to start with a DB with a commonly used set of extensions.

**Comment by kiwicopple** [comment]
> we can do is remove the option to connect to template1

Let's not remove the option, just as long as we don't modify it ourselves. We want to keep PG as close to "raw" implementation as possible

> there does not seem to be any template functionality whatsoever for schemas

Cool, no probs on this one. We will solve it with our pre-made code snippets.

I'll close this one. Great investigation and it looks like no more action required. Will be good to turn this into a blog post if you have time (e.g. "What are postgres templates?")
