### ISSUE TITLE
Alternative strategy for Improved CI Build and Deployment times

### ISSUE THREAD

**Issue by DMills27** [supabase/postgres#1078]
# Chore

## Describe the chore

The current setup uses Github Actions to build and deploy from this repository. However, it suffers from issues like needing to rerun the entire pipeline to debug or test changes, leading to unnecessary wait times instead of caching unchanged results. Additionally, the pipelines themselves aren't necessarily the most optimised since they run on [vCPUs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#:~:text=GitHub%2Dhosted%20runner%20is%20a%20new%20virtual%20machine%20(VM)%20hosted%20by%20GitHub%20with%20the%20runner%20application%20and%20other%20tools%20preinstalled).

I suggest [Garnix](https://garnix.io/) as an alternative for (certain aspects of) the CI process. Garnix is a Nix based CI build tool. In order to use it one simply needs to have a `flake.nix` file in the repository under consideration. In making this suggestion I'm not arguing for overhauling the existing architecture but simply offering an alternative to the current build process that will work in a more performant manner while not intruding on what already exists, aimed mainly at those who wish to self-host. This comes with a number of benefits, such as:

- Blazingly fast build times through [higher levels of parallelism](https://gvolpe.com/blog/garnix/#:~:text=Garnix%20has%20more%20powerful%20machines%20than%20Github%2C%20and%20that%20in%20turn%2C%20enables%20higher%20parallelism.%20Additionally%2C%20rather%20than%20vCPUs%2C%20we%20use%20CPU%20shares) as well as making use of CPU shares, rather than vCPUs.
- Sharing the same cache among multiple targeted repositories. 
- Making it much easier to deploy sophisticated integration and E2E NixOS tests akin to [this one](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/mysql/mysql-replication.nix) which starts a primary MySQL instance and synchronises two secondary instances. It then simulates downtime by stopping one secondary instance and adding data to the primary, then restarts and re-synchronises the secondary instance. Tests like these are useful for testing the robustness of database migrations.
- Allowing one to seamlessly [debug failed builds](https://garnix.io/docs/deployments#debugging-failed-builds) since Garnix provisions a server upon each build, which one can SSH into and figure out what went wrong. Disclaimer: This is a paid feature though.

Both of these options can exist alongside one another and provide points of comparison and contrast. Moreover, they can supplement one another as well since Garnix supports [integration with pre-existing Github actions](https://garnix.io/docs/gh-actions) by specifying it in the `garnix.yaml` file of the repository which makes it possible to offlet some of the work done by Github Action to Garnix to reduce overall time spent on different aspects of the build process. 

I forked this repository and to see how long it would take for Garnix to build and it took around ~20 minutes for the flake alone. I didn't try to integrate the other Github actions because it was onerous to do so since some of them needed me to set-up secrets, etc.

<p align="center"> 
<img width="600" height="400" alt="Screenshot 2024-07-31 at 10 10 12 AM" src="https://github.com/user-attachments/assets/a6a9fee8-0050-4b32-bded-c98b937db8a0">
</p>

The second time it took even shorter since it remembered the packages that were built from a previous commit, and produced the build in a fraction of the time it took on the initial run.

<p align="center">
<img width="600" alt="Screenshot 2024-07-31 at 12 54 26 PM" src="https://github.com/user-attachments/assets/64b1bf11-9c45-45fd-bd44-21b30b50f566">
</p>

**Comment by olirice** [comment]
thanks for opening

close with explanation in https://github.com/supabase/postgres/pull/1079#issuecomment-2261355276

but feel free to follow up if you'd like to discuss further
