### ISSUE TITLE
Fix customization link in documentation

### ISSUE THREAD

**Issue by lb-ovc** [supabase/postgres#1085]
# Improve documentation

## Link 
https://github.com/supabase/postgres/wiki

## Describe the problem
Link under the "Customization" section is pointed to https://github.com/supabase/postgres/tree/feature/supabasePostgresV1.0/ansible/files which does not exist

**Comment by olirice** [comment]
the wiki is out of date and we'll be deprecating it in favor of a (WIP) more fleshed out README

In light of that I'm going to close, but thank you for reporting it!
