### ISSUE TITLE
Procedural language extensions can't be enabled locally

### ISSUE THREAD

**Issue by olirice** [supabase/postgres#1094]
When running the test suite via
```
nix flake check -L
```

Some extensions fail to enable.

```sql
plv8
plcoffee
plls
```
all throw the error `could not load library`... `symbol not found in flat namespace`

To reproduce
```
nix run .#start-server 15
```
in another terminal
```
nix run .#start-client 15
```
and finally
```
create extension plv8;
```
<img width="1097" alt="Screenshot 2024-08-06 at 10 18 11 AM" src="https://github.com/user-attachments/assets/02474f04-79e4-4cc8-9e65-53f80cc7d8bf">

**Comment by samrose** [comment]
PR to close this issue https://github.com/supabase/postgres/pull/1117
