### ISSUE TITLE
Wiki links not working

### ISSUE THREAD

**Issue by omeroy** [supabase/postgres#1102]
# Bug report

## Describe the bug

The wiki links from the README.md are not working. For Example:

- https://github.com/supabase/postgres/wiki
- https://github.com/supabase/postgres/wiki/Docker
- https://github.com/supabase/postgres/wiki/AWS-EC2

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/supabase/postgres?tab=readme-ov-file#install
2. Check the links to the wiki

## What I was looking for?
- Instructions on how to build and run the supabase/postgres repository (using Docker)

**Comment by olirice** [comment]
the wiki was several years out of date and not maintained
we removed it yesterday favor of the README

The repo is undergoing some significant changes in the build system currently so things are out-of-sync but we're finalizing that transition and the docs will get the attention they deserve in the next month or so

**Comment by omeroy** [comment]
@olirice 
Is there any other documentation at the moment, how to build and run https://github.com/supabase/postgres using Docker?
