### ISSUE TITLE
Package pg_duckdb for review

### ISSUE THREAD

**Issue by olirice** [supabase/postgres#1106]
This task is to package (but not ship) [pg_duckdb](https://github.com/duckdb/pg_duckdb) to evaluate it locally and check interop with Supabase S3 compatible Storage

**Comment by samrose** [comment]
This is in process about 70%

Ran into some issues with the Makefile assumptions about deps and installation, and so will need to patch that on build

**Comment by docteurklein** [comment]
Hi! Are you writing a nix derivation for pg_duckdb? Because I tried [here](https://github.com/docteurklein/pgpim/blob/76615c313106570911100e0949ea9a729f41a1f1/flake.nix#L26-L55) without success.

The compilation works fine, but the installPhase seems to fail with:

```pg_duckdb> /nix/store/ifzwv2xqwdnv1gz87rxkizi67py5p3vj-coreutils-9.4/bin/mkdir -p '/nix/store/r0kvgrg6j84jwva3vcisvc6ggwbvwmi4-postgresql-16.2-lib/lib'
pg_duckdb> /nix/store/ifzwv2xqwdnv1gz87rxkizi67py5p3vj-coreutils-9.4/bin/mkdir -p '/nix/store/wwp41hdca4bwpsczq47a7bzj19pr63fz-postgresql-16.2/share/postgresql/extension'
pg_duckdb> /nix/store/ifzwv2xqwdnv1gz87rxkizi67py5p3vj-coreutils-9.4/bin/mkdir -p '/nix/store/wwp41hdca4bwpsczq47a7bzj19pr63fz-postgresql-16.2/share/postgresql/extension'
pg_duckdb> /nix/store/ifzwv2xqwdnv1gz87rxkizi67py5p3vj-coreutils-9.4/bin/install -c -m 755  pg_duckdb.so '/nix/store/r0kvgrg6j84jwva3vcisvc6ggwbvwmi4-postgresql-16.2-lib/lib/pg_duckdb.so'
pg_duckdb> /nix/store/ifzwv2xqwdnv1gz87rxkizi67py5p3vj-coreutils-9.4/bin/install: cannot create regular file '/nix/store/r0kvgrg6j84jwva3vcisvc6ggwbvwmi4-postgresql-16.2-lib/lib/pg_duckdb.so': Permission denied
pg_duckdb> make: *** [/nix/store/wwp41hdca4bwpsczq47a7bzj19pr63fz-postgresql-16.2/lib/pgxs/src/makefiles/../../src/Makefile.shlib:422: install-lib-shared] Error 1
```

**Comment by riderx** [comment]
I'm waiting for this like Christmas 🎄

**Comment by samrose** [comment]
This is packaged. Closing. Thanks for feedback folks!

**Comment by riderx** [comment]
When can we expect that to be released @samrose ?

**Comment by samrose** [comment]
> When can we expect that to be released @samrose ?

No ETA yet. We needed to package to evaluate. But we’ll be sure to announce if we end up using this!

**Comment by riderx** [comment]
Understand, could we have maybe issue to track progress on that ?
Generally any columnar db truely open source will solve my problem as user pf supabase cloud

**Comment by reveritas** [comment]
Commenting as it's been a few months, and I echo the sentiment that having a columnar storage extension for the managed Supabase offering would be amazing. It would really reduce storage costs and increase the performance for large analytical workloads. Is there any update about the extension being made available?

**Comment by riderx** [comment]
I got taught that will arrive soon

**Comment by reveritas** [comment]
Hopefully "soon" means very soon! I've been evaluating the process of self-hosting Supabase just to integrate pg_duckdb, but if this is in the works I'll stick with the cloud offering for now.

**Comment by julioxavierr** [comment]
The streets need this!

**Comment by riderx** [comment]
I saw on X paul testing ducklake. And he say they are working on it but not more
