### ISSUE TITLE
Create "latest" docker tags for each major version

### ISSUE THREAD

**Issue by andrasbacsai** [supabase/postgres#1131]
# Chore

## Describe the chore

Currently there is no latest, 15, 14... docker image tags available. So if someone would like to have the latest version of 15, they need check the exact version number like `15.6.1.113`.

Would it be possible to add such tags? I can help with a PR if needed.

**Comment by olirice** [comment]
@samrose  I know there was some back and forth on this internally. Could you remind me what the tradeoff is?

**Comment by samrose** [comment]
@olirice thank you yes, we do need a latest tag. I’ll address it asap

**Comment by samrose** [comment]
@olirice now that we just have 1 AMI release, it should be no issue to use "latest" tag in builds. Using "latest" will help assure that builds do not get out of sync, in a nutshell

**Comment by samrose** [comment]
@olirice we decided to create a major version tag instead of "latest" at least for the medium term future, because we'll likely be carrying multiple versions of postgres for a time. If that doesn't seem right to you please let me know.

**Comment by olirice** [comment]
makes sense to me
feel free to close this if that's the resolution
