### ISSUE TITLE
Chore: update Github description to supabase.com

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/postgres#114]
# Chore

## Describe the chore

update Github description  from [supabase.io](https://supabase.com) to [supabase.com](https://supabase.com)

<img width="1392" alt="Screen Shot 2021-12-16 at 3 19 32 PM" src="https://user-images.githubusercontent.com/70828596/146443489-003d7c60-8563-4e35-8a88-0aa6d4b2f074.png">

**Comment by inian** [comment]
Updated @Isaiah-Hamilton
