### ISSUE TITLE
Wiki is not public

### ISSUE THREAD

**Issue by rantoniuk** [supabase/postgres#1176]
https://github.com/supabase/postgres/blob/develop/README.md?plain=1#L59
but wiki is not public and therefore not accessible :(

**Comment by samrose** [comment]
We'll be cleaning up documentation soon here, and will be pushing the docs right to this repo. We no longer use the wiki feature, but instead will include markdown documents here.

**Comment by AntonOfTheWoods** [comment]
@samrose , any idea when "soon" might be? Could this be kept open until it is actually updated, so we know this has been addressed (I was going to open another ticket)?

**Comment by AntonOfTheWoods** [comment]
@samrose , some of the readmes are also not up-to-date, like https://github.com/supabase/postgres/blob/develop/nix/docs/use-direnv.md, which appears to not have been migrated when `nix-postgres` was merged. As an example, `.envrc` appears to *not* be in the `.gitignore`, and there is no `.envrc.recommended`.
