### ISSUE TITLE
Install and enable the safeupdate extension by default

### ISSUE THREAD

**Issue by inian** [supabase/postgres#124]
https://pgxn.org/dist/safeupdate/

**Comment by dragarcia** [comment]
Looks to be already installed via [here](https://github.com/supabase/postgres/blob/develop/ansible/tasks/postgres-extensions/09-pg-safeupdate.yml) and at the [latest version](https://github.com/supabase/postgres/blob/develop/ansible/vars.yml#L64) (1.4)

**Comment by inian** [comment]
Ah weird I didnt see this when doing `select * from pg_extension`. Let's enable it for default for new projects?

**Comment by dragarcia** [comment]
yea, looks to be active as soon as it's placed in `shared_preload_libraries`. Here's a [PR](https://github.com/supabase/postgres/pull/125)

**Comment by steve-chavez** [comment]
https://github.com/supabase/postgres/pull/125 is too harsh imo, some tools have migrations that do full table DELETEs and this change would make those fail. Also loading it by using `shared_preload_libraries` will require a db restart in case any user wants to remove it.

How about isolating the change?

```sql
-- would just affect postgrest usage
ALTER ROLE authenticator SET session_preload_libraries = 'safeupdate';
```

**Comment by dragarcia** [comment]
You're right, having it activated for everything might cause trouble down the road. Shall we just target PostgREST for now internally with Steve's query above?

**Comment by inian** [comment]
Yup, that seems like a good tradeoff to make!

**Comment by dragarcia** [comment]
Alright, put up a [PR](https://github.com/supabase/postgres/pull/128) to reverse the changes. Will put up [another internal PR](https://github.com/supabase/infrastructure/pull/3700) shortly to apply `safeupdate` to PostgREST queries.
