### ISSUE TITLE
Issue with pgmq Extension Installation – Request for Assistance

### ISSUE THREAD

**Issue by hotkaybee** [supabase/postgres#1294]
### Discussed in https://github.com/orgs/supabase/discussions/30091

<div type='discussions-op-text'>

<sup>Originally posted by **hotkaybee** October 25, 2024</sup>
I’ve encountered an issue while trying to add the pgmq extension via the dashboard. Unfortunately, it’s not listed among the available extensions. As a workaround, I attempted to install it using SQL with the following command:
`CREATE EXTENSION pgmq;`
However, this approach also failed, returning the following error:
```
ERROR: 0A000: extension "pgmq" is not available  
DETAIL: Could not open extension control file "/usr/share/postgresql/15/extension/pgmq.control": No such file or directory.
```
I’ve spent a considerable amount of time troubleshooting, referencing the documentation, and exploring possible solutions, but without success. The fact that pgmq is mentioned in the documentation yet unavailable is quite frustrating.
Could you please address this issue as soon as possible or provide an alternative solution? Your prompt assistance would be greatly appreciated.
![image](https://github.com/user-attachments/assets/61cbc830-c319-4701-be1a-6d141b94eb6d)
![image](https://github.com/user-attachments/assets/507a2415-eb4b-4684-86a7-99181a62c501)
</div>

**Comment by frissonlabs** [comment]
Have you tried following the guide here?

https://database.dev/plpgsql/pgmq

**Comment by samrose** [comment]
Hi there. Thank you for reaching out to us for assistance. pgmq has been packaged and documented, and tested, but is still in the process of being rolled out for general usage. Thus it is not yet available for activation in instances. Once it's announced officially, then you would be able to use it in all of the documented ways. We apologize for the frustration you've experienced. Please hang in there and watch for announcements on the official release of this, and then you'll be up and running using it.

**Comment by samrose** [comment]
@hotkaybee `pgmq` is now part of the supabase/postgres bundle as of https://github.com/supabase/postgres/releases/tag/15.8.1.019 and is now available in all zones on our hosted platform. Closing issue. Feel free to re-open or start another if you need to.
