### ISSUE TITLE
Is there option to enable Timescale with TSL license on the postgres image?

### ISSUE THREAD

**Issue by virtuman** [supabase/postgres#1381]
# Bug report

I don't know if I can't find it in the docs, but is there an option for a TimescaleDB extension to be enabled with "timescale" license on this image? I use timescale extensively and apache license is very limiting and most features are not available.

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

run a container with supabase/postgres image

psql -U postgres -d postgres
```
CREATE EXTENSION IF NOT EXISTS timescaledb;
ALTER SYSTEM SET timescaledb.license = 'timescale';
SELECT pg_reload_conf();
```
i keep on getting error that library file for tsl license does not exist 

## Expected behavior

It should switch the license type

## System information

any supabase/postgres image, i primarily use 15.6

**Comment by samrose** [comment]
@virtuman unfortunately the TSL is such that we are not able to distribute that version with this distribution/release. The only compatible version is Timescale Apache.
