### ISSUE TITLE
Set up with Layer CI - https://show.layerci.com

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres#17]
Same as this issue: https://github.com/supabase/realtime/issues/29

I think it makes more sense to start with Postgres only.

1. Log in
2. click "Submit project"
3. Post title: "Postgres by Supabase"

It makes sense to just copy the config from one of the other projects. Click the project, then in the popup switch to the "Configuration" tab, copy it and use it for this.

**Comment by ColinChartier** [comment]
Hm, "EXPOSE WEBSITE" only works for HTTP protocols right now, are you trying to expose the actual Postgres port?

**Comment by kiwicopple** [comment]
good finding this @ColinChartier - yeah I am.

Is there a way to pull this off your store? I can try again with something web-based

**Comment by ColinChartier** [comment]
Sure, I can remove it for you if you'd like.

The work you've done for the database part is good otherwise!

**Comment by ColinChartier** [comment]
```
FROM vm/ubuntu:18.04

# To note: Layerfiles create staging servers, *not* containers!

# install the latest version of Docker, as in the official Docker installation tutorial.
RUN apt-get update && \
    apt-get install apt-transport-https ca-certificates curl software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && \
    apt-get update && \
    apt install docker-ce

RUN docker run -d -p 5432:5432 supabase/postgres

EXPOSE WEBSITE http://localhost:5432
```

**Comment by kiwicopple** [comment]
Go for it - I'll switch over to another repo
