### ISSUE TITLE
Upgrade to pgbouncer 1.17

### ISSUE THREAD

**Issue by darora** [supabase/postgres#176]

**Comment by Lakshmipathi** [comment]
@darora, We are still using `1.16.1`, should we update and give it a try on staging env? Do you have any concerns with `1.17`?

**Comment by darora** [comment]
Go for it, no concerns

**Comment by pashkinelfe** [comment]
Already 1.17 as per https://github.com/supabase/postgres/blob/develop/ansible/vars.yml
