### ISSUE TITLE
Digital Ocean Build Does not work

### ISSUE THREAD

**Issue by shintaii** [supabase/postgres#19]
Hi Just spinned up your Postgres image. It does not work. Commands cannot be executed as root. postgresql is not a known command. when running from /bin directly error is shown that no config is found.

**Comment by dragarcia** [comment]
Hi! Thanks for the feedback. Could you provide us with the exact steps you have taken for us to reproduce this issue?

**Comment by shintaii** [comment]
Sure. I created a droplet on DO. I spinned online. Then i accessed it via my SSH key as root. Trying to execture the commands and nothing happens. It was a 1cpu 1gb Droplet.

**Comment by awalias** [comment]
Testing now

**Comment by awalias** [comment]
hi @shintaii the postgres tools are installed under the user `postgres` so you can use `sudo -u postgres psql postgres` to run the command as the `postgres` user

or run `su postgres` to switch into the `postgres` user for the duration of your bash session

let us know if this helps? there's also some more info here: [https://marketplace.digitalocean.com/apps/supabase-postgres#getting-started](https://marketplace.digitalocean.com/apps/supabase-postgres#getting-started)

**Comment by awalias** [comment]
closing for now, please re-open if this solution didn't work
