### ISSUE TITLE
Digital Ocean Build Not Working Currently

### ISSUE THREAD

**Issue by jackkeller** [supabase/postgres#200]
Trying the marketplace creation on [digitalocean](https://marketplace.digitalocean.com/apps/supabase-postgres) and there is no postgres user, nor is postgres even installed.

**Tried 3 Attempts:**
- Ubuntu 18.04 w/ [Marketplace](https://marketplace.digitalocean.com/apps/supabase-postgres)
- Ubuntu 18.04 and adding **Supabase Realtime** from the Marketplace tab
- Ubuntu 20.04 and adding **Supabase Realtime** from the Marketplace tab

Currently on the Ubuntu 20.04 VM and following the getting started. Here is what I see after logging in via SSH

```bash
root@supabaserealtime:~# sudo -u postgres psql postgres
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
root@supabaserealtime:~# su postgres
No passwd entry for user 'postgres'
root@supabaserealtime:~# apt list --installed | grep postgres

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

root@supabaserealtime:~# apt list --installed | grep vim

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

vim/now 2:8.0.1453-1ubuntu1.3 amd64 [installed,upgradable to: 2:8.0.1453-1ubuntu1.8]
vim-common/now 2:8.0.1453-1ubuntu1.3 all [installed,upgradable to: 2:8.0.1453-1ubuntu1.8]
vim-runtime/now 2:8.0.1453-1ubuntu1.3 all [installed,upgradable to: 2:8.0.1453-1ubuntu1.8]
vim-tiny/now 2:8.0.1453-1ubuntu1.3 amd64 [installed,upgradable to: 2:8.0.1453-1ubuntu1.8]
```

After getting no hits on postgres I figured I'd see if vim was installed and got data back.

**Comment by hachete01** [comment]
I had the exact same issue just earlier today. I noticed that after selecting Supbase postgres from the marketplace page (to create the droplet), in the dialog to create the droplet no image is selected. I searched for the image in the marketplace from this page, and only Supabase Realtime appears.
![Screen Shot 2022-05-12 at 3 51 50 PM](https://user-images.githubusercontent.com/100227926/168157345-b807e387-cea2-4114-99ee-ff9f92ab4746.png)

**Comment by jackkeller** [comment]
I feel like I took that step as well, I will give it another go tomorrow to see if that's the step I'm missing.

**Comment by hachete01** [comment]
To clarify, my point was to confirm the existence of the issue you raised, by adding that the image for Supabase Postgres is not currently selectable to be installed via one-click on a droplet, therefore new installations this way are not possible (it can be installed in a droplet with Docker). Supabase Realtime I believe is a different product than Supabase Postgres, one that is intended to complement an existing Postgres installation with the ability to listen in realtime.

**Comment by CoenNengerman** [comment]
I am experiencing the same issue. I was eager to try Supabase, but unfortunately this doesn't seem to work. I can use the Docker, but the docker doesn't have WAL-G

**Comment by dragarcia** [comment]
Hello all

Apologies for the delayed reply. The Digital Ocean droplet image has not been updated for a while now as we have shifted our focus to Docker as the recommended option for self-hosting Supabase. One of the reasons is that this image, unlike the Docker offering, does not have all the features Supabase has to offer. The droplet image only offers the database component and none of the other services such as Auth, Storage, Realtime, and more.

With this, we apologise for the confusion caused with the droplet image. We have started the process of discontinuing the marketplace offerings of this image on both the AWS and Digital Ocean marketplaces as well as updating any related guides and articles to avoid any further confusion in the future. These offerings should be fully removed from these marketplaces over the next few weeks.

For more information on the overview of our self-hosted setup, you can refer to our [documentation here](https://supabase.com/docs/guides/hosting/overview). You can refer [here](https://supabase.com/docs/guides/hosting/docker) on how to set up Supabase through Docker.

Thank you all for your understanding and we appreciate your feedback.

**Comment by dragarcia** [comment]
> I am experiencing the same issue. I was eager to try Supabase, but unfortunately this doesn't seem to work. I can use the Docker, but the docker doesn't have WAL-G

@CoenNengerman with regards to this, thank you for the feedback. We'll look into getting WAL-G working for the Docker set up as well.

**Comment by olirice** [comment]
closing as no longer applicable (DO not supported)
