### ISSUE TITLE
Request PostgreSQL Anonymizer extension

### ISSUE THREAD

**Issue by magick93** [supabase/postgres#204]
Please add the Anonymizer extension. 

https://pgxn.org/dist/postgresql_anonymizer/0.12.0/

License - https://gitlab.com/dalibo/postgresql_anonymizer/-/blob/master/LICENSE.md

https://github.com/supabase/supabase/discussions/6789

**Comment by dragarcia** [comment]
Hi @magick93

* Thanks for adding it to the Postgres Extensions discussion thread via https://github.com/supabase/supabase/discussions/679#discussioncomment-3322325.
* Any further updates with regards to the extension will be sent through the discussion thread.
* We'll be closing this issue to maintain a single source for any updates and for gauging the overall interest of the community.
* Feel free to use the discussion thread if you would like to discuss anything further with regards to the extension.
