### ISSUE TITLE
pg_timetable: Advanced scheduling for PostgreSQL

### ISSUE THREAD

**Issue by magick93** [supabase/postgres#206]
# Feature request

pg-timetable - see https://pg-timetable.readthedocs.io/en/master/README.html#main-features

https://github.com/cybertec-postgresql/pg_timetable/blob/master/LICENSE

**Comment by steve-chavez** [comment]
@magick93 We already provide [pg_cron](https://github.com/citusdata/pg_cron), can you elaborate on why you want to use pg_timetable?

**Comment by magick93** [comment]
Hi @steve-chavez 

Just to clarify my position - my motivation is to improve Supabase. IMO Supabase is awesome. There are some really useful extensions for postgres, and may of which are already being offered by Supabase. In this case I'm suggesting pg_timetable as a more feature rich alternative to pg_cron. Both have their place and value.

The features that pg_timetable offers, quoted from their docs, are:

- Tasks can be arranged in chains
- A chain can consist of built-int commands, SQL and executables
- Parameters can be passed to chains
- Missed tasks (possibly due to downtime) can be retried automatically
- Support for configurable repetitions
- Built-in tasks such as sending emails, etc.
- Fully database driven configuration
- Full support for database driven logging
- Cron-style scheduling at the PostgreSQL server time zone
- Optional concurrency protection
- Task and chain can have execution timeout settings

**Comment by dragarcia** [comment]
Hi @magick93 

* Do upvote its entry on the Postgres Extensions if you haven't: https://github.com/supabase/supabase/discussions/679#discussioncomment-2961251
* Let's continue any further discussion there as well to have a single source to gauge the interest of the community.
* We'll push further updates through the discussion thread as well.

Thanks!
