### ISSUE TITLE
Extension python3u

### ISSUE THREAD

**Issue by althaf004** [supabase/postgres#211]
Hi,

We have all our existing functions done with plpython3u. We are forced to use Keycloak for the authentication, for which we had to use [keycloak sdk ](https://github.com/marcospereirampj/python-keycloak) . Is there anyway we can start migrating our functions to supabase with plpython3u extension. 

If anyone has a quick idea on fix, please help.

**Comment by kiwicopple** [comment]
Hey @althaf004 - moving this one to the `postgres` repo. 


I believe that plpython is an untrusted extension, so we won't be able to provide it in our repo - will let one of the maintainers confirm this

**Comment by dragarcia** [comment]
Hi @althaf004 

Apologies for the delayed response. We would just like to confirm what has been mentioned above: the `plpyton3u` extension is still considered to be an [untrusted extension](https://www.postgresql.org/docs/current/plpython.html) and therefore won't be part of our list of extensions anytime soon. As mentioned [here](https://github.com/supabase/supabase/discussions/2239#discussioncomment-975613), it is hard to limit the functionality of such untrusted extensions and a malicious user can make the platform unsafe for everyone.

I will be closing this issue for now, but do feel free to open it once more if you have any further questions.
