### ISSUE TITLE
Push the latest image pg 14 image to dockerhub

### ISSUE THREAD

**Issue by olirice** [supabase/postgres#216]
Please push the latest image to dockerhub so we can update the cli's docker image and keep it in sync with the hosted platform

Ref:
https://github.com/supabase/pg_graphql/issues/160

**Comment by david-plugge** [comment]
And please add the arm64 arch :)

**Comment by w3b6x9** [comment]
> Please push the latest image to dockerhub so we can update the cli's docker image and keep it in sync with the hosted platform
> 
> Ref: [supabase/pg_graphql#160](https://github.com/supabase/pg_graphql/issues/160)

done: https://hub.docker.com/layers/postgres/supabase/postgres/14.1.0.34/images/sha256-cc7f5b281f65561d47ba85dd41b1703f81d20550390d63fe4290ab1901db7d35?context=explore

**Comment by w3b6x9** [comment]
> And please add the arm64 arch :)

@david-plugge feel free to create another issue to address that.
