### ISSUE TITLE
Support for data directory on attached volume

### ISSUE THREAD

**Issue by awalias** [supabase/postgres#22]
DO wizard gives the option to attach a volume when provisioning the droplet,

I would like to have postgres use this as the default data directory:

- either automatically on startup
- or give instructions in 'getting started' for how to switch the data directory to my attached volume

I imagine the same/similar thing is possible on AWS

**Comment by dragarcia** [comment]
## Tested instructions for using an attached volume
https://github.com/supabase/postgres/wiki/Digital-Ocean#attaching-and-using-a-volume

Have sent an update to the DO Marketplace listing to include instructions linking to the wiki page above. Should take a few days.

**Comment by dragarcia** [comment]
[feature/#22_data_directory_volume](https://github.com/supabase/postgres/tree/feature/%2322_data_directory_volume) contains how a volume can be automatically created and attached to a droplet during droplet creation. A detailed explanation can be found [here](https://github.com/supabase/postgres/blob/feature/%2322_data_directory_volume/do_scripts/README.md).
