### ISSUE TITLE
Push latest arm64 image to dockerhub

### ISSUE THREAD

**Issue by david-plugge** [supabase/postgres#226]
Please push the latest image with arm64 architecture to dockerhub to support the newest features on selfhosted platforms.
The latest arm image is on version 14.1.0.15.

https://github.com/supabase/supabase/issues/4887

My current solution:

https://github.com/supabase/supabase/issues/2954#issuecomment-1183391492

**Comment by soedirgo** [comment]
We now have `supabase/postgres` images for  linux/arm64
