### ISSUE TITLE
Function not found

### ISSUE THREAD

**Issue by k0shk0sh** [supabase/postgres#229]
Starting from yesterday the 17th of June, some of my RPC functions are not working anymore and I receive the following error: 

```
 {
   "message": "Could not find the public.get_user() function or the public.get_user function with a single unnamed json or jsonb parameter in the schema cache",
   "code": null,
   "details": null,
   "hint": "If a new function was created in the database with this name and parameters, try reloading the schema cache."
 }
```

I was wondering if there is any internal change happened from yesterday to today that could cause this? 

P.S: other functions are working fine.

function: 
```
create function get_user(user_id uuid)
    returns TABLE(id uuid, username text, full_name text, avatar text, followings bigint, followers bigint)
    language sql
as
$$
select u.id,
       u.username,
       u.full_name,
       u.avatar,
       (select count(*) from friends as f where f.follower = user_id),
       (select count(*) from friends as f where f.following = user_id)
from users as u
where u.id = user_id
  and is_not_blocked(user_id)
limit 1;
$$;
```

**Comment by k0shk0sh** [comment]
hmm, it works from console but not from flutter anymore.

**Comment by darora** [comment]
Hi there-if this is related to a project hosted by Supabase, please create a support ticket via your dashboard.

Based on the fact that other functions are being executed fine, my first guess would be to verify if the permissions on the function in question have been updated recently.

**Comment by steve-chavez** [comment]
Could you please retry your rpc requests? This was likely related to https://github.com/supabase/supabase/issues/7293, which was recently fixed.

**Comment by steve-chavez** [comment]
Also, please retry your rpc requests. This could have been related to https://github.com/supabase/supabase/issues/7293, which was recently fixed.

**Comment by k0shk0sh** [comment]
@steve-chavez it most definitely was it. it works now 🤷🏼
