### ISSUE TITLE
XML functions unsupported

### ISSUE THREAD

**Issue by boredom101** [supabase/postgres#235]
# Bug report

## Describe the bug

When I try to use an XML function, it states that the XML feature is unsupported

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run an SQL snippet like: `SELECT xmlelement(name foo);`
2. See error

## Expected behavior

I expected that the XML function would return expected result.

## Screenshots

![screenshot of error](https://user-images.githubusercontent.com/20235408/178384359-354f505e-730c-44ec-93f8-fdd331dd966f.png)

## Additional context

I think this is caused by postgres not being compiled with libxml.

**Comment by boredom101** [comment]
Hello, I don't want to be a bother, but it seems the only change needed for this bug is to change this line to add `--with-libxml`: https://github.com/supabase/postgres/blob/develop/ansible/tasks/setup-postgres.yml#L71

**Comment by steve-chavez** [comment]
@boredom101 Yes, that should be enough. I suggest to make a PR.

**Comment by boredom101** [comment]
The fix was released, and it works.
