### ISSUE TITLE
Add h3 extension to the extensions list

### ISSUE THREAD

**Issue by kav** [supabase/postgres#245]
# Feature request

We'd love to use h3 for some simple distance calculations using H3 https://h3geo.org/ . For a primer on how this differs from other Geospatial libraries see the introductory blog post here: https://eng.uber.com/h3/

## Describe the solution you'd like

I'd love https://github.com/bytesandbrains/h3-pg added to the extensions list so I could turn it on or off at will

## Describe alternatives you've considered

Our three alternatives are to off-load h3 processing to a secondary function for filtering and sorting post-postgres or self-host supabase and install the extension there or just use postgis which works but is a fair bit more complex and a bit difficult to master for our use case.

## Additional context

H3 is pretty dang cool and something I suspect anyone doing location focused apps on Supabase would really appreciate having it. Even seeing it in the extensions lists and googling it could be pretty awesome for folks just getting started.

More on h3:
https://foursquare.com/article/all-about-h3-your-questions-answered/
https://foursquare.com/article/how-to-use-h3-for-geospatial-analytics/

Thanks for taking the time!

**Comment by burmecia** [comment]
The h3 extension has been posted on https://github.com/supabase/supabase/discussions/679#discussioncomment-2602385, can you upvote it?

**Comment by dragarcia** [comment]
Hi @kav 

* With the extension being kept track through https://github.com/supabase/supabase/discussions/679#discussioncomment-2602385, any further updates with regards to it will be sent through the discussion thread instead.
* We'll be closing this issue to maintain a single source for updates.
* Feel free to use the discussion thread if you have any further questions with regards to the H3 extension.

Thanks!

**Comment by gudeso2023** [comment]
Dear H3 Team,

Is there an easier way to add H3 extension to Postgres using Windows, I have spent a lot of time trying but without success. The main method I used was pgxnclient. Thanks Ori
