### ISSUE TITLE
Add features for DB admins

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres#29]
# Feature request

Now that our SQL editor is becoming more full featured, I think it will be necessary for DB admins to put restrictions on the database to prevent beginner errors. This is to start a list of possible features that DB admins will require.

- safeupdate: https://github.com/eradman/pg-safeupdate

While we're at it, we can add some other requested extensions and anything planning to use in our features:

- pg_cron [comment](https://github.com/supabase/postgres/issues/5#issuecomment-671621891)

**Comment by dragarcia** [comment]
All top requested extensions mentioned in #5 have already been covered by previous versions. Will be closing this. Any additional feature requests for `v0.14.0` can be directed in #32.
