### ISSUE TITLE
Unable to create index

### ISSUE THREAD

**Issue by kylerummens** [supabase/postgres#292]
# Bug report

## Describe the bug
I am trying to create an index on a table in my database. I am getting the following error message:
`could not extend file "base/12974/1228183": No space left on device`

query: `create index form_version_index on public.recipient_forms (form_version)`

**Comment by darora** [comment]
@kylerummens - per the error message, your PG instance has run out of disk space. If this is on the hosted platform, please open a support ticket through the dashboard and we can investigate why it wasn't automatically handled.
