### ISSUE TITLE
Set default encoding and collation to UTF-8

### ISSUE THREAD

**Issue by doctorpangloss** [supabase/postgres#30]
# Feature request

Consider something along the lines of

```sql
update pg_database set encoding = 6, datcollate = 'en_US.UTF8', datctype = 'en_US.UTF8' where datname = 'template0';
update pg_database set encoding = 6, datcollate = 'en_US.UTF8', datctype = 'en_US.UTF8' where datname = 'template1';
```

from https://www.postgresql.org/docs/9.5/manage-ag-templatedbs.html

## Describe the solution you'd like

This makes some sensible defaults for the `create database` command. For some reason this fixes acute problems on Docker for Windows Desktop hosts along with adding this to many different containerized applications, including probably yours:

```dockerfile
ENV LANGUAGE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
```

## Describe alternatives you've considered

```dockerfile
FROM supabase/postgres:0.13.0
COPY 99-database-customizations.sql /docker-entrypoint-initdb.d/
```

**99-database-customizations.sql**:
```sql
update pg_database set encoding = 6, datcollate = 'en_US.UTF8', datctype = 'en_US.UTF8' where datname = 'template0';
update pg_database set encoding = 6, datcollate = 'en_US.UTF8', datctype = 'en_US.UTF8' where datname = 'template1';
```

**Comment by dragarcia** [comment]
Just pushed the changes to the branch `develop`. This will eventually be part of the upcoming docker version `supabase/postgres:0.14.0` 

---
>acute problems on Docker for Windows Desktop hosts

Not entirely sure but [this](https://superuser.com/a/999151) may have been a plausible reason why.
