### ISSUE TITLE
Re-enable Vault extension

### ISSUE THREAD

**Issue by alex-ketch** [supabase/postgres#307]
# Chore

## Describe the chore

I'd like to see the Supabase [Vault extension](https://github.com/supabase/vault) included in the image again.

https://github.com/supabase/postgres/blob/92de0b6b2daf7961d2ced9a5f6b4f82b8ae5390c/ansible/tasks/setup-extensions.yml#L67-L68

## Additional context

I don't have the context for why, but PR #278 temporarily [disabled the Vault extension](https://github.com/supabase/postgres/pull/278#issuecomment-1221927439).
Was the extension deemed too experemimental, or was there an issue with the build?

**Comment by dragarcia** [comment]
Hi @alex-ketch 

We're still in the midst of performing and finalizing usability and security testing for the Supabase Vault extension. Rest assured, we'll keep you posted once it has been reenabled on the images.

**Comment by alex-ketch** [comment]
Thanks for the background, saves me from tinkering and trying to make a PR :) 
And no worries, really appreciate all the work you do!

**Comment by Lakshmipathi** [comment]
Hi @alex-ketch, Vault is now available in beta https://supabase.com/blog/vault-now-in-beta  

> Using the Vault
> 
> You'll see the Vault appear in the Dashboard over the next month. If you want to use Vault today, email [growth@supabase.com](mailto:growth@supabase.com) and we'll enable it on your account. Vault is available for all customers (including the Free-tier).

Will go ahead and mark this as resolved.
