### ISSUE TITLE
add pg_idkit extension

### ISSUE THREAD

**Issue by gperdomor** [supabase/postgres#318]
# Feature request

## Additional context

Based on supabase blog [post](https://supabase.com/blog/choosing-a-postgres-primary-key#benchmarking-id-generation-with-uuid-ossp-and-pg_idkit), would be nice having this extension in the docker image

**Comment by iveshenry18** [comment]
Seconding this request—bit of a bait-and-switch to recommend this in a blog post but not support it!

Nonetheless, really appreciate what this team has built.

**Comment by olirice** [comment]
The bar for adding new extensions to the platform is very high. In pg_idkit's case, we're instead pushing for adopting the functionality via a [trusted language extension](https://github.com/aws/pg_tle) to put the control in users' hands. We're developing tooling to make that process smoother but in the short term you can copy the implementations of `gen_random_uuidv6` or `gen_random_uuidv7` from [here](https://github.com/aws/pg_tle) for use in your projects

That project is also available on [dbdev](https://database.dev/)
