### ISSUE TITLE
Refactoring: Separate long running parts of playbook-docker.yml into separate RUN statements inside dockerfile

### ISSUE THREAD

**Issue by jimkoen** [supabase/postgres#322]
# Chore

## Describe the chore

I'm currently bisecting supabase/postgres in order to trace [this bug](https://github.com/supabase/supabase/issues/9378) that has started appearing somwhere arround ~v*.55 of the image.

Attempting to build older commits has, until now, lead to several build errors during image builds on Mac OSX (even though I'm using docker, which is super weird, but what gives). This is particularly annoying as it happens right after the two main stages of the playbook have finished (building SFCGAL and plv8). 

It would probably be a good idea to refactor what is currently one gigantic playbook importing a large number of task files, which then again import more task files, into smaller playbooks that get executed in separate RUN statements.
This would be much more in line with dockers idea of image layers and the docker build cache.
And the most obvious benefit being that I don't have to wait 1h in order to know if a build worked like it's the mid 90's.

If developers aprove this idea, I would like to claim this issue.

Edit: Obviously you don't necessaril have to have separate playbooks files. I think there is a way to execute specific plays from a playbook file with multiple plays. But I also just saw that you use tags for your internal installation, thats ofc also an option.

**Comment by olirice** [comment]
sorry no one got back to you on this issue

we've recently re-implemented our AMI and docker builds away from ansible so this is no longer applicable + it looks like the source of the bug has been resolve in https://github.com/supabase/supabase/issues/9378

closing for now but if you're still experiencing the issue please let me know
