### ISSUE TITLE
Update PostGIS to 3.2.0+

### ISSUE THREAD

**Issue by exotfboy** [supabase/postgres#323]
Hi:

As postgis document said:

>Enhanced: 3.2.0 srid as an extra optional argument was added. Older installs require combining with ST_SetSRID to mark the srid on the geometry.

Any plan to update the postgis plugin?

**Comment by pashkinelfe** [comment]
It's already 3.3.2 as per https://github.com/supabase/postgres/blob/develop/ansible/vars.yml
