### ISSUE TITLE
Backport Docker builds for PG13

### ISSUE THREAD

**Issue by soedirgo** [supabase/postgres#336]
# Feature request

## Is your feature request related to a problem? Please describe.

Right now we only publish PG14 images. Once we start supporting PG15, we'll need to support >1 major versions anyway - might as well do it for PG13 as well since we still support it.

## Describe the solution you'd like

Build Docker images for PG13

## Describe alternatives you've considered

n/a

## Additional context

This is needed for Supabase CLI's local dev to work properly on PG13 projects: https://github.com/supabase/cli/issues/460

**Comment by olirice** [comment]
closing as no longer needed
