### ISSUE TITLE
Support for more images

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres#4]
This issue is for tracking requests/demand for more images. Give a thumbs up if you want an image built.

Please refrain from adding comments unless you are adding an image which isn't already listed.

**Comment by kiwicopple** [comment]
Docker

**Comment by kiwicopple** [comment]
GCP

**Comment by bergkvist** [comment]
[Docker app](https://github.com/docker/app) (which is currently part of Docker CLI 19.03.0 as an experimental feature)
```
DOCKER_CLI_EXPERIMENTAL=enabled docker app run <app-name>
```

**Comment by rienheuver** [comment]
Not sure if this is the right place, but would love an Ubuntu (20.04) build, so it can be run on any VPS

**Comment by Jaakkonen** [comment]
A slimmer alpine-based variant would be nice to have for smaller deployment size!

**Comment by ventsyv** [comment]
I'm working on a ubi9-micro based image. Officially supported ubi9 based image would be great.

**Comment by olirice** [comment]
we will be working on minimizing the size of the docker image but don't plan to tackle any other platforms for public use at this point
