### ISSUE TITLE
RFC: new extensions

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres#45]
Possible new extensions:

- `is_jsonb_valid`: https://github.com/supabase/supabase/discussions/679#discussioncomment-348469
- `IP4R`: https://github.com/supabase/supabase/discussions/679#discussioncomment-566220
- https://github.com/postgrespro/rum RUM provided a enhanced GIN Index for common search function
- https://github.com/amutu/zhparser zhparser is a PostgreSQL extension for full-text search of Chinese language
- pgRouting https://github.com/supabase/supabase/discussions/679#discussioncomment-688348
- https://github.com/iCyberon/pg_hashids for obscuring ids
- supascript: https://github.com/burggraf/SupaScript

My current thoughts:

- We should do pgRouting now, since we want to be useful for mapping services in the future
- we should add a bunch of extensions around text search + dictionaries - great differentiator
- supascript could be useful

**Comment by bhvngt** [comment]
Do you have any plans to include [pglogical](https://www.2ndquadrant.com/en/resources/pglogical/). From whatever little I know, it looks like it may bring in some more flexibility to supabase realtime in terms of filtering logical replication etc.

**Comment by dragarcia** [comment]
Hi @bhvngt! 👋 

No plans at the moment but it could always be a possibility down the road. For now, could you help me add it to the list [here](https://github.com/supabase/supabase/discussions/679)? We keep track and consolidate all of our extension requests on this discussion page. 

Thanks!
