### ISSUE TITLE
Additional AMI "bundles"

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres#46]
## Context

We'd like to build a few different bundles for: a) the AWS marketplace and b) internal usage.

## Bundles

We would like to produce AMI bundles

- `Postgres` -> this one we already have
- `Postgres` + `PgBouncer`
- `Postgres` + `PostgREST`
- `Postgres` + `PgBouncer` + `PostgREST`

## Marketplaces

The top priority is to produce these images for the AWS marketplace. We can target other marketplaces (DO, GCP etc) in a separate issue.

**Comment by dragarcia** [comment]
Will add to https://github.com/supabase/postgres/pull/44

**Comment by dragarcia** [comment]
Btw, do we already have names in mind to easily distinguish one from the others? At the top of my head, all I could think off are:

|   | Supabase Postgres  | PgBouncer  | PostgRest  |  
|---|:---:|:---:|:---:|
| Supabase Postgres |  ✔️   | ❌    | ❌   |  
| Supabase Postgres: PgBouncer Bundle  |   ✔️ |  ✔️  | ❌    |  
| Supabase Postgres: PostgRest Bundle |   ✔️ |  ❌  |  ✔️   |  
| Supabase Postgres: Comple Bundle |  ✔️  | ✔️   | ✔️   |

**Comment by kiwicopple** [comment]
I think those names are good - just make sure it's `PostgREST` rather than `PostgRest` to fit their branding.

**Comment by dragarcia** [comment]
Will be closing this as we will discontinue our public AMI builds in favor of our Docker offerings as the recommended option for self-hosting Supabase. ([ref](https://github.com/supabase/postgres/issues/200#issuecomment-1155018270))

For more information on the overview of our self-hosted setup, you can refer to our [documentation here](https://supabase.com/docs/guides/hosting/overview). You can refer [here](https://supabase.com/docs/guides/hosting/docker) on how to set up Supabase through Docker.
