### ISSUE TITLE
plv8 v3.0.0 fails to build for ARM instances

### ISSUE THREAD

**Issue by dragarcia** [supabase/postgres#47]
Using these steps:
1. Ensure PostgreSQL is installed beforehand.
2. `apt install build-essential ca-certificates curl git-core gpp cpp pkg-config apt-transport-https cmake libc++-dev libc++abi-dev libc++1 libglib2.0-dev libtinfo5 libc++abi1 ninja-build python`
3. `git clone https://github.com/plv8/plv8.git`
4. `cd plv8 && git checkout v3.0.0` 
5. `make`
6. `make install`

Step 6) `make` eventually returns an error `clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'`
![image](https://user-images.githubusercontent.com/26374889/121529418-f6a13b00-ca2e-11eb-9f3b-69367ccd87c9.png)

### Instance used
- AWS r6g.2xlarge
- Ubuntu 20.04 LTS

### Analysis
[Changes made to the Makefile](https://github.com/plv8/plv8/commit/977712aa6751c83738f92f82438607e903927e88#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52) in this [commit](https://github.com/plv8/plv8/commit/977712aa6751c83738f92f82438607e903927e88) could have most likely affected the build configuration for ARM instances. 

### Temporary Solution
Reverted back to 3.0.alpha by building from a [commit prior to the above commit](https://github.com/plv8/plv8/commit/3656177d384e3e02b74faa8e2931600f3690ab59). This worked as per normal.

**Comment by dragarcia** [comment]
@burggraf

**Comment by inian** [comment]
Should we open an issue in the plv8 repo Angelico?

**Comment by dragarcia** [comment]
got it, just created on [here](https://github.com/plv8/plv8/issues/444).

**Comment by vejja** [comment]
Hi @dragarcia 
Have you been able to build plv8 v3.1.2 ?
If yes it would be super exciting to upgrade the plv8 version that is being packaged into the docker image. 
This would bump the v8 engine version from v7.4 to v9.7, adding many useful modern JS features (e.g. private class methods, optional chaining, nullish coalescing, Array.includes, Intl API, ...)

**Comment by Lakshmipathi** [comment]
Right now, we are using pretty recent version of plv8 commit (https://github.com/supabase/postgres/blob/develop/ansible/vars.yml#L81) That seems the last commit https://github.com/plv8/plv8/commits/r3.1.  I'll go ahead and mark this as resolved. if you disagree, please feel free to re-open or create new issue.
