### ISSUE TITLE
Add pg_repack extension instead of inbuilt VACCUM

### ISSUE THREAD

**Issue by kevbook** [supabase/postgres#476]
# Feature request

In production databases, you don’t want to use the `VACUUM FULL` operation because it blocks other activities in the database. Another alternative when you want the storage reclaimed rather than just be available for reuse is using the [pg_repack](https://reorg.github.io/pg_repack/) extension.
 
It's also available with RDS and Aurora PostgreSQL that cleans up dead tuples.
https://aws.amazon.com/blogs/database/remove-bloat-from-amazon-aurora-and-rds-for-postgresql-with-pg_repack/

**Comment by mqp** [comment]
This extension is also valuable because it provides a way to `CLUSTER` without locks.

**Comment by pashkinelfe** [comment]
I think it's safe enough and worth adding. PR: https://github.com/supabase/postgres/pull/492

**Comment by pcnc** [comment]
Hello everybody,

This has rolled out to the Supabase platform today, available for newly created projects, or ones which are paused and then unpaused (to get re-provisioned using the updated server image).
