### ISSUE TITLE
ansible task "setup-postgres.yml" requires "pkg-config"

### ISSUE THREAD

**Issue by Towerful** [supabase/postgres#495]
# Bug report

## Describe the bug

I'm trying to run the ansible playbook against my own server.  
The task "Postgres - configure" inside the "setup-postgres.yml" file was failing with a requirement of "pkg-config".  
This was installing against a basic Ubuntu install from https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img

## To Reproduce

create a basic VM using https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img with 16 cores and suitable memory.  
Run the playbook against the VM.

## Expected behavior

Not to error

## To Fix

Adding the `- pkg-config` to the "Postgres dependencies" task of "setup-postgres.yml" solves this issue.

## System information

Running ansible from a 4 core VM running the same Ubuntu image.

## Additional context

I'm very new to ansible, so I don't know if there is a better place to include this dependency? Perhaps it's used in other tasks? I feel like it is used when compiling a lot of the postgres extensions.

**Comment by pcnc** [comment]
Hi @Towerful - thanks for reporting this!

Also added `pkg-config` to `setup-postgres.yml` - https://github.com/supabase/postgres/pull/503
