### ISSUE TITLE
Ansible task "wal-g - deps" in "setup-wal-g.yml" requires curl

### ISSUE THREAD

**Issue by Towerful** [supabase/postgres#505]
# Bug report

## Describe the bug

Using a basic install of Ubuntu 20.04, the task "wal-g - deps" in `setup-wal-g.yml` fails due to curl not being installed  
https://github.com/supabase/postgres/blob/develop/ansible/tasks/setup-wal-g.yml#L44  
The issue is then ignored, and ansible keeps running (I'm not sure if it completes)

## Expected behavior

Perhaps curl should be an apt pkg install?  
I'm not sure how many of these things are just "expected as part of the system".  
I think some tasks use wget, other use curl

**Comment by olirice** [comment]
Sorry that no one got back to you on this issue

Since reporting, we have switched to nix as our build tool and have deprecated the ansible flow

Closing as no longer supported
