### ISSUE TITLE
Improve documentation on version management

### ISSUE THREAD

**Issue by philmas** [supabase/postgres#516]
Currently the documentation is not covering what version one should use for the selfhosted docker containers. As there a lot of integrations/add-ons for the postgres database some mismatch occurs or might occur. This should be addressed in the documentation including small fixes.

I assume the hosted platform was in sync with the docker builds. However, as I am struggling with setting it up and some smaller bugs had been fixed by using new image versions, it seems that either the problem has been resolved or shifted.

Could you clarify?

**Comment by olirice** [comment]
this repository is a collection of build tooling for the postgres image (including docker images). For more info on how to self host check out the [self hosting docs](https://supabase.com/docs/guides/self-hosting) and [supabase/cli](https://github.com/supabase/cli)
