### ISSUE TITLE
Skip removing apt lists / run updates on each layer?

### ISSUE THREAD

**Issue by jbergstroem** [supabase/postgres#578]
# Chore

## Describe the chore

A potential time saving improvement for building containers could be to stop removing the downloaded apt list for the builder / ccache image and avoid updating in each image. I doubt the package repositories have changed between the first image being created and subsequent layer reuse.

## Additional context

Happy to open a PR if the approach makes sense. Perhaps there's another reason each step does "update && rm".

**Comment by olirice** [comment]
Sorry no one got back to you on this

Closing as out-of-date. Please re-open if still applicable
