### ISSUE TITLE
connection via pgbouncer takes 10x longer to load

### ISSUE THREAD

**Issue by kopy-kat** [supabase/postgres#601]
# Bug report

## Describe the bug

Related to issue #203 (which is closed now): I'm currently encountering an issue where, holding everything else constant, if I switch from a connection to port 5432 to a connection to post 6543 using pg_bouncer, the same query takes 10x longer. This occurs in a local environment, but haven't been able to test in production yet.

## Tech information

- Nextjs v13.2.1
- prisma v4.11.0

**Comment by sweatybridge** [comment]
Could you share more details about your local development setup?

We officially support the CLI for local development but it doesn't run pgbouncer locally at all.

**Comment by kopy-kat** [comment]
I was not using the CLI, but using prisma within a serverless frontend (NextJS) framework

**Comment by olirice** [comment]
Closing as pg_bouncer has been replaced with supavisor. Please follow up if this issue is still relevant and I misunderstood
