### ISSUE TITLE
Coolify fails on first boot as well as Docker Portainer

### ISSUE THREAD

**Issue by miguelgargallo** [supabase/postgres#701]
Coolify fails on first boot as well as Docker Portainer

It would be great a well Docker documentation to one click dockerfile with .env on secrets to try this for the masses

**Comment by olirice** [comment]
Sorry no one got back to you on this

> Coolify fails on first boot as well as Docker Portainer

I don't follow. Could you please include reproduction steps, an explanation of what you expected, and what actually happened?

Closing for now as this is quite old but I'll re-open if the issue is still present
