### ISSUE TITLE
Supbase postgres ssl root certificate relies on legacy Common Name field

### ISSUE THREAD

**Issue by SpareShade** [supabase/postgres#73]
# Bug report
The SSL root cert provided on by supabase.co (https://app.supabase.io/project/<id>/settings/database) relies on legacy Common Name field which is deprecated in the RFC 2818
## Describe the bug
using golang 1.6.n SSL connection to supabase DB fails
Please have a look at
rancher/rke2/issues/775

ps. I wasn't sure where exactly to report this

**Comment by darora** [comment]
Thanks for the report @SpareShade , we'll try to have this fixed soon. I'm guessing it'll be fixed for newer projects; an in-place migration for existing ones will likely be quite hard.

**Comment by egor-romanov** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
