### ISSUE TITLE
Update `pg_cron` to allow Sub-Minute Scheduling

### ISSUE THREAD

**Issue by Marviel** [supabase/postgres#740]
# Chore

## Describe the chore

`pg_cron` as pulled by the Supabase CLI at the current version does not allow sub-minute scheduling.

The container attached to the Supabase CLI should be updated to a version that supports sub-minute scheduling, as in the link below.

## Additional context

https://github.com/supabase/supabase/blob/f3f51cc506990fb191eb1bd6037cea6332736336/apps/www/_blog/2023-06-09-supabase-beta-update-may-2023.mdx#L67

**Comment by GaryAustin1** [comment]
https://github.com/supabase/postgres/pull/634
Supabase tried and had to back it out.

**Comment by vongohren** [comment]
I assume here are multiple needs on this update: 
https://github.com/orgs/supabase/discussions/7892#discussioncomment-7114939

And here: https://github.com/supabase/supabase/issues/17736

**Comment by olirice** [comment]
Closing as completed

Supabase projects (local and hosted) now run pg_cron 1.6.2 with sub-minute scheduling
