### ISSUE TITLE
Set up plv8

### ISSUE THREAD

**Issue by kiwicopple** [supabase/postgres#8]
https://github.com/plv8/plv8

- [x] Docker
- [x] Packer

**Comment by dragarcia** [comment]
## Implementation notes
- Uses plv8 version `r3.0alpha`. Creator/ maintainer assures that it should be [production ready](https://github.com/plv8/plv8/issues/390).
- Steps to install plv8 follow steps listed out [here](https://github.com/clkao/docker-postgres-plv8/blob/master/12-2/Dockerfile).
- From trial and error, minimum RAM required to install plv8 would be 1 GB.
