### ISSUE TITLE
Extension "supautils" has no installation script nor update path for version "0.1.0"

### ISSUE THREAD

**Issue by vitabaks** [supabase/postgres#815]
I created a new project to get the latest version of the database, \
then when checking the possibility of creating extensions, I found that there is an error in the extension "supautils":

```
ERROR:  22023: extension "supautils" has no installation script nor update path for version "0.1.0"
```

**Comment by olirice** [comment]
supautils has been updated to no longer present as a target for `create extension`, its functionality is enabled by default on all projects

If that doesn't resolve this issue please let me know how we can help
