### ISSUE TITLE
Use Dockerfile to build the image

### ISSUE THREAD

**Issue by vHanda** [supabase/postgres#82]
Hi. Usually most Docker images are built using a Dockerfile. It would be nice if either -

* The `supabase/postgres` image could also be built via a Dockerfile, thereby simplifying the build process

or 

* The readme could be updated to educate users like me about the reason for choosing ansible over a Dockerfile.

**Comment by olirice** [comment]
Sorry no one got back to you on this

We have recently revamped our docker build and are in the process of documenting all the changes.

In the short term you can build the docker image locally like this:
```
docker build -f Dockerfile-156 -t supa-15-6 .
```
better docs to follow
