### ISSUE TITLE
【bug】Postgres crashes when enable the vector extension

### ISSUE THREAD

**Issue by xhb** [supabase/postgres#927]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Postgres crashes, when enable the vector extension

## To Reproduce

1. install supabase cli
2. supabase init 
3. supabase start
4. psql postgresql://postgres:postgres@127.0.0.1:54322/postgres
postgres=> create extension vector;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> 

## Expected behavior

1.create extension vector;
2.create table posts (
  id serial primary key,
  title text not null,
  body text not null,
  embedding vector(384)
);
3.exec above SQL, without error.

## Screenshots

![截屏2024-04-01 12 55 50](https://github.com/supabase/postgres/assets/3167082/f03d734e-3af2-4ed9-8697-7ee0d297fb4f)
![截屏2024-04-01 12 56 49](https://github.com/supabase/postgres/assets/3167082/776f3e2b-2f06-4fa4-b3f9-ff07daf31c1e)
![截屏2024-04-01 12 56 55](https://github.com/supabase/postgres/assets/3167082/217935d0-340f-4f3f-8f54-27226fc86330)

## System information

- OS: [ubuntu22.04]
- supabase cli: [1.151.1]
- supabase services

        SERVICE IMAGE      │        LOCAL         │ LINKED
  ─────────────────────────┼──────────────────────┼─────────
    supabase/postgres      │ 15.1.0.147           │ -
    supabase/gotrue        │ v2.143.0             │ -
    postgrest/postgrest    │ v12.0.1              │ -
    supabase/realtime      │ v2.25.66             │ -
    supabase/storage-api   │ v0.46.4              │ -
    supabase/edge-runtime  │ v1.38.0              │ -
    supabase/studio        │ 20240301-0942bfe     │ -
    supabase/postgres-meta │ v0.80.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -

**Comment by olirice** [comment]
Could you please confirm if this is still present on the latest version of the CLI running supabase/postgres:15.1.1.86?

I was not able to reproduce

**Comment by olirice** [comment]
Merging with #1074 
please follow up there
