### ISSUE TITLE
docker image pgvector enabling fails

### ISSUE THREAD

**Issue by wiemann** [supabase/postgres#998]
latest docker image "supabase/postgres:15.1.0.72_arm64" doesn't allow enabling pgvector.
```
docker run  -e  POSTGRES_PASSWORD=password1234 --name supabase-postgres supabase/postgres
```

```sql
CREATE EXTENSION "vector";
```
returns

```ERROR:  could not open extension control file "/usr/share/postgresql/14/extension/vector.control": No such file or directory```

**Comment by olirice** [comment]
we don't maintain `latest` tags so you have to specify the version of the docker image you want
full list of tags available here https://hub.docker.com/r/supabase/postgres/tags

e.g.
```
docker run  -e  POSTGRES_PASSWORD=password1234 --name supabase-postgres supabase/postgres:15.1.1.69
```

**Comment by olirice** [comment]
I'm going to close this for now but please follow up if you have any trouble getting that to work
